config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'

  resources :recipes do
        collection do
      get 'pantry'
    end
     match :recipes_using_pantry, via: [:get], on: :collection
  end

  #probably will want to restrict the routes later
  resources :ingredients

resources :meals do 
   collection do
      get 'planner'
    end 
    match :batch_create, via: [:post], on: :collection
  end

  get  '/signup',  to: 'users#new'
  get '/charts', to: 'users#charts'

  resources :users 

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
	belongs_to :recipe, inverse_of: :meal_plans

#in controller @time_period = {"last week" => 7, "two weeks ago" => 14}
#For now, let's assume last week is between yesterday and 7 days ago

scope :date_filter, ->(number){
			n = number.to_i
 			start_date = (n + 1).days.ago #since it's beginning and end need to start 1 earlier
 			end_date = (n - 6).days.ago #1 day ago 7-6
 		if number.present? && n >= 7
 	 		where(meal_date: start_date..end_date )
 	 	elsif number.present? && n < 7
 	 		 where(meal_date: start_date..1.days.ago )
 	    else
 	    	where(meal_date: 8.days.ago..1.days.ago ) 
 	    end } 

	    scope :number_of_meals, ->(number) {
	    	if number.present?
	    		number = number.to_i
	    	else
	    		number = 7
	    	end
	    	number
	    }

	    scope :last_week_meals, ->{where(meal_date: 8.days.ago..1.days.ago ).to_a }

	    scope :meal_order, -> {order(:meal_date)}


def self.meal_plan_generator(number)

#don't forget the direction from which you are coming joins must start from the has many side
#e.g. Recipe has_many :meal_plans --> Recipe.joins(:meal_plans)

#create a meal plan for next X days 
	meals_requested = self.number_of_meals(number)

	@last_week_meals = self.last_week_meals

	@this_week_meals = []

	grain_counts = {}
	protein_counts = {}
	
	#make it time out if it tries to many times. Probably base it on the length of recipes table

	while(@this_week_meals.length < meals_requested)
		
		rando_recipe = self.get_random_recipe

		#if they don't have anything on file for last week, go ahead and return false
		if @last_week_meals.empty?
			lw_match = false
		else
			lw_match = self.compare_to_week(@last_week_meals,rando_recipe)
		end


		# we really only want to check each criteria if the criteria before it is met
		#first check for matches with last week and this week
		#then check for grain and protein counts
		
		if lw_match == true
			next
		elsif @this_week_meals.empty?
			#tw_match = false we can actually add without checking anything else
			#but we also want to move on to the next item
			add_to_list(@this_week_meals, rando_recipe)
		else
			tw_match = self.compare_to_week(@this_week_meals, rando_recipe)
		end

		if(tw_match == false)
			grain_max = self.check_component_part(@this_week_meals,grain_counts,rando_recipe.grain.name)
		else
			next
		end

		if(grain_max == false)
			protein_max = self.check_component_part(@this_week_meals,protein_counts,rando_recipe.protein.name)
		else
			next
		end

		if(protein_max == false)
			add_to_list(@this_week_meals,rando_recipe)
		else
			next
		end

	end

	@this_week_meals	
end
	def self.get_random_recipe
		#change id column to recipe_id so it has consistent naming to last week meals
		@random_recipe = Recipe.select("id as recipe_id, name, difficulty_level, grain_id, protein_id").offset(rand(Recipe.count)).first
	end

def self.compare_to_week(arr,item)
	match = true
	arr.each do |a|

		if(a.recipe_id == item.recipe_id)
			break
		elsif(a.recipe_id != item.recipe_id && arr.index(a) == arr.index(arr.last))
			match = false
		else
			next
		end
	end
	match
end

def self.add_to_list(arr, item)
	arr.push(item)
end

def self.check_component_part(arr,component_hash, type)
	#example method with arguments
	#check_component_part(@this_week_meals,rando_recipe,grain_counts,rando_recipe.grain.name)
		
	max = false
		if component_hash.has_key?(type) && component_hash.values_at(type)[0]< 3
			component_hash[type] = component_hash[type]  + 1
			#grain_max is still false so don't need to add anything
		elsif component_hash.has_key?(type) 
			max = true
		else
			#grain_max is still false so don't need to mention. just set the type to 1
			component_hash[type] = 1
		end

	max	
end

	def self.batch_create(post_content)
		meal_values = JSON.parse(post_content)
	  # begin exception handling
	  begin
	    # begin a transaction on the  mp model
	    MealPlan.transaction do
	      # for each student record in the passed json
	      meal_values.each do |meal_hash|
	        # create a new student
	        MealPlan.create!(meal_hash)
	      end # json.parse
	    end # transaction
	  rescue
	    # do nothing
	  end  # exception handling
	end  # batch_create

end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
	def index
		@meal_plans = MealPlan.meal_order.date_filter(params[:date_filter])
		#last week, 7 days before date to 14 days before date
		@time_period = {"last week" => 7, "two weeks ago" => 14}
	end

	def planner
		@number_of_meals = {"one meal" => 1, "five meals" => 5, "seven meals" => 7}
		@this_week_meals = MealPlan.meal_plan_generator(params[:number_of_meals])		
		@grains = Grain.all							   
	end

	def show
		@meal_plan = MealPlan.find(params[:id])
	end
	
	def new
		@meal_plan = MealPlan.new

		respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @meal_plan }
	    end
	end

	def create
		
		 @meal_plan = MealPlan.new(meal_plan_params)

		 #still need to figure out where to redirect when posting from ajax
	    
	    respond_to do |format|
	      if @meal_plan.save
	        format.html { redirect_to @meal_plan, notice: 'meal_plan was successfully created.' }
	        format.json { render json: @meal_plan, status: :created, meal_plan: @meal_plan }
	        format.js
	      else
	        format.html { render action: "new" }
	        format.json { render json: @meal_plan.errors, status: :unprocessable_entity }
	      end
	    end
	end

  def batch_create 
    # call the batch create method within the meal plan model
    success = MealPlan.batch_create(request.raw_post)
    # return an appropriate response
    respond_to do |format|
	    if success
	    	format.html { redirect_to meal_plans_path, notice: 'recommendations were successfully
	            	 added' }
	      format.json { render json: {success: 'meal plans added'}, status: :created }
	    else
	     format.json { render json: {failed: 'meal plans not added'}, status: :unprocessable_entity }
	    end
	end
  end

	private

	def meal_plan_params
      params.require(:meal_plan).permit(:recipe_id, :meal_date)
    end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/views/meal_plans/_form.html.erb
<%= form_for @meal_plan do |f| %>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-4">
        <div class="field">
           <%= f.label :recipe %>
            <br />
            <%= f.collection_select :recipe_id, Recipe.order(:name), :id, :name %>
        </div>
        <div class="field">
            <%= f.label :date %>
            <br />
            <%= f.date_select :meal_date %>
        </div>
        </br>
          <div class="actions">
            <%= submit_tag nil, class: 'btn btn-primary' %>
          </div>
  </div>
</div>
<% end %>

app/views/meal_plans/index.html.erb
<%= render 'shared/side_links.html.erb' %>
<div class="row">
          <div class="col-sm-3"></div>
          <div class="col-sm-6">
          <% @meal_plans.each do |meal| %>
            <li> <%= link_to meal.recipe.name, meal.recipe %> - <%= meal.meal_date %></li>
          <% end %>
          </div>
   <div class="col-sm-2">
          <div class="row">
              <div class="col-sm-12">
                <strong>Filter by Date</strong>
              </div>
              <div class="col-sm-12">
                <% @time_period.each_pair do |text, number| %>
                  <li>
                    <%= link_to "#{text}", meal_plans_path(date_filter: number), class: 'label label-primary' %>
                  </li>
                <% end %>
              </div>
          </div>
      </div>
</div>

app/views/meal_plans/new.html.erb
<%= render 'shared/side_links.html.erb' %>
<div class="container">
  	<div class="row">
	    <div class="col-sm-1"></div>
		<div class="col-sm-8">
		  	<h3 class='blue'>Add Meal Plans</h3>
	 	</div>
	</div>
		<%= render 'form' %>
	  </br>
	</br>

app/views/meal_plans/planner.html.erb
<%= render 'shared/recipe_link.html.erb' %>

<div class = "row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 heading">  
    <h4>This Week's Meal suggestions are:</h4>
  </div>
</div>
</br>
<div class = "row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="row subheading">
      <div class="col-sm-6">Meal</div>
    </div>
  </div>
</div>  
<div class = "row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 meal-suggestions">
    <% @this_week_meals.each do |meal| %>
      <div class="row meal">
        <div class="col-sm-6">
          <%= link_to meal.name, recipe_path(meal.recipe_id) %>
           <%=  hidden_field_tag :recipe_id, value: meal.recipe_id %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-3">
    <div class="row">
       <div class="col-sm-12"> <strong>Filter by Date</strong></div>
          <div class="col-sm-12">
              <% @number_of_meals.each_pair do |text, number| %>
                <li>
                  <%= link_to "#{text}", planner_meal_plans_path(number_of_meals: number), class: 'label label-primary' %>
                </li>
              <% end %>
          </div>
        </div>
    </div>
  </div>
</br>
</br>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">Filter by grain:</div>
</div>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
     <% @grains.each do |grain| %>
      <% unless grain == @grains.last %>
       <%= link_to grain.name, planner_meal_plans_path(grain_requests: grain.id) %>,
      <% else %>
        <%= link_to grain.name, planner_meal_plans_path(grain_requests: grain.id) %>
      <% end %>
    <% end %>
  </div>
</div>
  <%# Need to figure out appropriate layout for this section %>
  <%#<div class="col-sm-3"><p>Summary: This week, you're making <% @difficult_items.length %><%#</div></p> %>

    <%# 
    It is impossible to have more than 3 items with a value of 2 or higher, so you only
    need 3 conditions. 
    
 %>

<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-3">
    <button class="btn btn-success save">
      Save Meal Plan
    </button>
  </div>
</div>
</br>
<script type="text/javascript"> 
$(function () {
    var saveButton = $('.save');


//currently basing date on tomorrow + 1 for each new recipe
   
   var date = new Date(Date.now());



    saveButton.on("click", function() {
        var hiddenElements = $( "body" ).find( ":hidden" ).not( "script" );

     var date = new Date(Date.now());
     var dataArr = [];
       // for now, doing regex to get the id val

        
       for(var i=0; i<hiddenElements.length; i++){
        var tempHash = {}
        var val = hiddenElements[i].value;
       // get the value only. returns an array, so get the first index of that array
        var recipeId = val.match(/\d+/g)[0];
        
     //   date is getting reset every time, so you only need to add 1
        date.setDate(date.getDate() + 1);
        var month = Number(date.getMonth()) + 1
           if(month < 10){
             month = "0" + month;
           }
        var dateDbFormat = date.getFullYear() + "-" + month + "-" + date.getDate();
        tempHash["recipe_id"] = recipeId;
        tempHash["meal_date"] = dateDbFormat;

       
         dataArr.push(tempHash);
       }
      
       $.ajax({
            url:'/meal_plans/batch_create',
             type: 'POST',
             dataType: 'json',
             contentType: 'application/json',
             data: JSON.stringify(dataArr),
              headers: {
               'X-Transaction': 'POST Example',
               'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
             },
         //    success handled by the controller
            error: function (jqXHR, textStatus, errorThrown) {
             //     may want to do flash instead
                 alert("could not save this meal");
             }
         });
    });

});

</script>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-2"><%= link_to "home", recipes_path %></div>
  <div class="col-sm-3"><%= link_to "See Last Week's Meals", meal_plans_path(date_filter: 7) %></div>
</div>