config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'

  resources :recipes do
        collection do
      get 'pantry'
    end
     match :recipes_using_pantry, via: [:get], on: :collection
  end

  #probably will want to restrict the routes later
  resources :ingredients

resources :meals do 
   collection do
      get 'planner'
    end 
    match :batch_create, via: [:post], on: :collection
  end

  get  '/signup',  to: 'users#new'
  get '/charts', to: 'users#charts'

  resources :users 

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	before_validation :titleize

	validates :user_id, presence: true

	validates :name, length: { minimum: 4 }, uniqueness: { scope: :user_id}

	belongs_to :user

	has_many :meals, inverse_of: :recipe

	has_many :recipe_ingredients
	
	has_many :ingredients, through: :recipe_ingredients

	scope :current_user_recipes, ->(current_user) {where('user_id = ?', current_user.id).order(:name)}

	scope :active_recipes, -> {where(active:true)}

	scope :times_eaten, -> (id){ joins(:meals).merge(Meal.meal_order).where('recipes.id =?', id).pluck('meals.meal_date') }

	scope :current_user_difficulty_of_recipes, -> (current_user) { 
		where('user_id = ?', current_user.id).where('active = ?', true).
		group(:difficulty_level).count }


	def self.current_user_active_recipes(current_user)
		current_user_recipes(current_user).active_recipes
	end

	def self.ingredients_in_active_recipes(current_user)
		Recipe.joins(:ingredients).where('user_id = ?', current_user.id).where('active = ?', true).group("ingredients.name").count
	end

	def self.ingredients_in_recent_active_recipe_meals(current_user)
		Recipe.select("ingredients.name").joins(:ingredients).joins(:meals).
		where('meals.meal_date between ? and ?', 31.days.ago, 1.days.ago).
		where(user_id:current_user.id,active:true).group("ingredients.name").count
	end

	def self.difficulty_level_of_recent_meals(current_user)
		Recipe.select("recipes.name").joins(:meals).
		where('meals.meal_date between ? and ?', 31.days.ago, 1.days.ago).
		where('recipes.user_id = ?', current_user.id).group(:difficulty_level).count
    end

    def self.recent_recipe_meals(current_user,isActive)
    	Recipe.select("recipes.name").joins(:meals).
    	where('meals.meal_date between ? and ?', 31.days.ago, 1.days.ago).
    	where('active = ?', isActive).where('recipes.user_id = ?', current_user.id).
    	group("recipes.name").count
    end
    
    def self.pantry_recipes(included,excluded,onlyActive,current_user)
    	
		included_ingredients = "(" + included.join(',') + ")"

		excluded_ingredients = "(" + excluded.join(',') + ")"
#Joining a recipe that has multiple ingredients will return multiple rows,
#so can't query not directly, we need to do a subquery to make sure a recipe with one of those ingredients it not included
		if onlyActive
			@pantry_recipes = Recipe.joins(:recipe_ingredients).where(recipe_ingredients: {ingredient_id: included}).where("recipe_ingredients.recipe_id 
				NOT IN (select recipe_ingredients.recipe_id from recipe_ingredients where recipe_ingredients.ingredient_id in #{excluded_ingredients})").where(active: true).where(user_id: current_user.id).group(:id).having("count(recipes.id) = ?", included.length)
		else
				@pantry_recipes = Recipe.joins(:recipe_ingredients).where(recipe_ingredients: {ingredient_id: included}).where("recipe_ingredients.recipe_id 
				NOT IN (select recipe_ingredients.recipe_id from recipe_ingredients where recipe_ingredients.ingredient_id in #{excluded_ingredients})").where(user_id: current_user.id).group(:id).having("count(recipes.id) = ?", included.length)
		end
	end
	protected
	def titleize
		self.name = name.titleize
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user_recipes, only: [:show, :edit, :update, :destroy]


	def index
		@recipes = Recipe.paginate(:page => params[:page], :per_page => 15).current_user_recipes(current_user)

	end

	def show
		@recipe = Recipe.find(params[:id])
		@times_eaten = Recipe.times_eaten(params[:id])
	end

	def new
		@food_groups = FoodGroup.order(:name)
		@ingredients = Ingredient.order(:name)
		@recipe = Recipe.new

		respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @recipe }
	    end
	end

	def edit
		@food_groups = FoodGroup.order(:name)
		@ingredients = Ingredient.order(:name)
		@recipe = Recipe.find(params[:id])
	end

	def create
	     @recipe = current_user.recipes.build(recipe_params)

	    respond_to do |format|
	      if @recipe.save
	        format.html { redirect_to recipes_path, notice: 'recipe was successfully created.' }
	        format.json { render json: @recipe, status: :created, recipe: @recipe }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @recipe.errors, status: :unprocessable_entity }
	      end
	    end
	end


	def update

	    @recipe = Recipe.find(params[:id])

	    respond_to do |format|
	      if @recipe.update(recipe_params)
	        format.html { redirect_to @recipe, notice: 'recipe was successfully updated.' }
	        format.json { head :no_content }
	        format.js 
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @recipe.errors, status: :unprocessable_entity }
	      end
	    end
	end

	
	def pantry
		@food_groups = FoodGroup.order(:name)
		@ingredients = Ingredient.order(:name)
	end

	def recipes_using_pantry
		onlyActive = false
		if params[:active] 
			onlyActive = true
		end
	 	included_ingredients = params[:included_ingredients].map { |item| item["id"] }

	 	if params[:excluded_ingredients]
	 		excluded_ingredients = params[:excluded_ingredients].map { |item| item["id"] }
	 	else
	 		excluded_ingredients = []
	 	end

	 	@pantry_ingredients = Ingredient.pantry_selected_ingredients(included_ingredients)

		@pantry_recipes = Recipe.pantry_recipes(included_ingredients, excluded_ingredients, onlyActive,current_user)	

	 	 respond_to do |format|
	       format.json { render json: @pantry_recipes }
	       format.js 
	    end	
	end

	private
	def recipe_params
      params.require(:recipe).permit(:name, :difficulty_level, { :ingredient_ids => [] }, :user_id, :active)
    end

    def correct_user_recipes
    	id = params[:id]
    	sql = "Select user_id from recipes where user_id = id"
    	@user_id = Recipe.select(:user_id).find(params[:id])
    	evaluate_auth_and_redirect(@user_id)
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-10 offset-1 col-md-4 offset-md-3">
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :difficulty_level %><br />
        <%= f.number_field :difficulty_level, max: 5, min: 0 %>
      </div>

   <label id="ingredients-label"><strong>Ingredients</strong></label>
   <% @food_groups.each do |food_group| %>
    <div class="food-groups-ingredients">
      <div class="food-group-label"> <%= link_to food_group.name, "#" %> <span class="fa fa-caret-down"></span></div> 
          <% @ingredients.where(food_group_id: food_group.id).each do |ingredient| %>
            <div class="field recipe-form-ingredient hidden-ingredient">
               <% if @recipe.ingredients.count > 0 && @recipe.ingredients.include?(ingredient) %>
                     <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id, {:checked => "checked"} %><%= ingredient.name %>
              <% else %>
                       <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id %> <%= ingredient.name %>
              <% end %>

            </div>
          <% end %>
        </div>
      <% end %>
    </br>
     <div class="field">
        <%= f.check_box :active, checked: @recipe.new_record? || @recipe.active? %>  <%= f.label :active %>
      </div>
      <div class="actions">
        <%= f.submit class: 'btn btn-primary form-button' %>
      </div>
  </div>
</div>
<% end %>
<script type="text/javascript">
$(function () {

  $('.food-group-label').on('click', function(event){
     event.preventDefault()
     $(this).find('span').toggleClass('fa-caret-down').toggleClass('fa-caret-up');
  $(this).closest('.food-groups-ingredients').find('.recipe-form-ingredient').toggleClass('hidden-ingredient');
   })

  });
</script>

app/views/recipes/_pantry_ingredients.html.erb
<div class="row"> Ingredients Selected: 
	<% ingredients.each do |ingredient| %>
		<%= ingredient.name %><% if ingredient != ingredients.last  %>,<% end %>
	<% end %>
</div>

app/views/recipes/_pantry_recipes.html.erb
<% recipes.each do |recipe| %>
	<div class='row pantry-recipe'>
		<%= link_to recipe.name, recipe_path(recipe) %> -
		<% recipe.ingredients.each do |ingredient| %>
			<%= ingredient.name %><% if ingredient != recipe.ingredients.last  %>,<% end %>
		<% end %>
	</div>
<% end %>
<footer><div class="row"><em> Don't have all the ingredients in one of these recipes? Make sure to mark those items in the exclude checklist</em></div></footer>

app/views/recipes/edit.html.erb
<div class="container">
  	<div class="row">
	    <div class="col-10 offset-1 col-md-8 form-header">
		  	<h2>Edit recipe</h2>
	 	</div>
	</div>
	<%= render 'form' %>
	  </br>
	</br>
	<div class="row">
		<div class="col-10 offset-1 col-3 offset-md-4"><footer><%= link_to 'Back', recipes_path %></footer></div>
	</div>
</div>

app/views/recipes/index.html.haml
%div{:class=> "row"}
	%div{:class => "col-10 offset-1 col-md-8 offset-md-3"}
		%h3 Recipes
%div{:class => "row"}
	%div{:class => "col-10 offset-1 col-md-8 offset-md-3"}
		-@recipes.each do |recipe|
			%li= link_to recipe.name, recipe_path(recipe)
		=will_paginate

app/views/recipes/new.html.haml
%div{:class => "row"}
	%div{:class => "col-10 offset-1 col-md-8 offset-md-3 form-header"}
		%h2 Add a Recipe
= render 'form'
%div{:class => "row"}
	%div{:class => "col-10 offset-1 col-md-5 offset-md-3"}
		%footer= link_to 'Back', recipes_path

app/views/recipes/pantry.html.erb
<div class="row">
    <div class="col-10 offset-1 col-md-6">
        <h3>Recipes with Ingredients You Have at Home</h3>
    </div>
</div>
<%= form_tag("/recipes/recipes_using_pantry", method: "get", remote: true) do  %>
<div class="row">
  <div class="col-10 offset-1 col-md-4 pantry-container">
   <label id="ingredients-label"><strong>You have:</strong></label>
   <% @food_groups.each do |food_group| %>
    <div class="food-groups-ingredients">
      <div class="food-group-label"> <%= link_to food_group.name, "#" %> <span class="fa fa-caret-down"></span></div> 
          <% @ingredients.where(food_group_id: food_group.id).each do |ingredient| %>
            <div class="field pantry-form-ingredient hidden-ingredient">
              <%= check_box_tag 'included_ingredients[][id]',ingredient.id, false, class: "select-ingredient" %> <%= ingredient.name %>
            </div>
          <% end %>
        </div>
      <% end %>
   <label id="ingredients-label"><strong>You don't have</strong></label>
   <% @food_groups.each do |food_group| %>
    <div class="food-groups-ingredients">
      <div class="food-group-label"> <%= link_to food_group.name, "#" %> <span class="fa fa-caret-down"></span></div> 
          <% @ingredients.where(food_group_id: food_group.id).each do |ingredient| %>
            <div class="field pantry-form-ingredient hidden-ingredient">
              <%= check_box_tag 'excluded_ingredients[][id]',ingredient.id, false, class: "exclude-ingredient" %> <%= ingredient.name %>
            </div>
          <% end %>
        </div>
      <% end %>
   <div id="pantry-active-checkbox" class="field">
        <%= check_box_tag 'active', true %> <label>Only Active Recipes</label>
   </div>
      <div class="actions">
         <%= submit_tag("Get Recipes", class: 'btn btn-primary form-button') %>
      </div>
    <% end %> <!-- end of form -->
  </div>
</div>
<div class="row">
      <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <div class="row">
          <div class="col-4 offset-8 col-sm-3 offset-sm-9 col-md-10 offset-md-2">
            <span class="close">&times;</span>
          </div>
           <div class="col-12 col-sm-10 offset-sm-1">
            <div class="row pantry-recipes">
            </div>
          </div>
        </div>
        
      </div>
    </div>
</div>
<script type="text/javascript">
$(function () {

  $('span').on('click', function(){
     $('.modal').attr('style','display: none');
  })
  $('.food-group-label').on('click', function(event){
      event.preventDefault()
      $(this).find('span').toggleClass('fa-caret-down').toggleClass('fa-caret-up');
      $(this).closest('.food-groups-ingredients').find('.pantry-form-ingredient').toggleClass('hidden-ingredient');
    });

  });
</script>

app/views/recipes/recipes_using_pantry.js.erb
$('.pantry-recipes').empty();
html = ""
 <% if @pantry_recipes.length == 0 %>
 	html += "<div class='col-12'><div class='row'><h5>No recipes match your list of ingredients. Try again with fewer included and/or excluded ingredients.</h5></div></div>";
 	$('.pantry-recipes').html(html);
 <% else %>
    html += "<div class='col-12'><div class='row'><h4> Recipes Using Selected Ingredients</h4></div></div><div class='col-12 selected-ingredients'></div><div class='col-12 pantry-recipes-list'></div>";
    $('.pantry-recipes').html(html);
    $('.pantry-recipes-list').html("<%= j render(partial: 'pantry_recipes', locals: { recipes: @pantry_recipes } ) %>");
 	$('.pantry-recipes .selected-ingredients').html("<%= j render(partial: 'pantry_ingredients', locals: { ingredients: @pantry_ingredients } ) %>"); 
 <% end %>

 $('.modal').attr('style','display: block');

app/views/recipes/show.html.erb
<div class="row">
   <div class="col-10 offset-1 col-md-6 offset-md-4">
    <h4><%= @recipe.name %></h4>
  </div>
</div>
<div class="row">
   <div class="col-10 offset-1 col-md-6 offset-md-4">
  		<% if @times_eaten.empty? %>
  	  		You have not yet made this recipe.
  	  	<% else %>
  	  		Last eaten on <%= @times_eaten.last %>.
  	  	<% end %>
  </div>
</div>
</br>
<div class="row">
   <div class="col-10 offset-1 col-md-6 offset-md-4">
      <% x = 1 %>
      <% unless @recipe.ingredients.empty? %> Main ingredients: 
          <% @recipe.ingredients.each do |ingredient| %>
              <% if x != @recipe.ingredients.length %>
                <%= ingredient.name %>,
              <% else %>
                <%= ingredient.name %>
              <% end %>
              <% x += 1 %>
          <% end %>
      <% end %>
  </div>
</div>
</br>
<div class="row">
  <div id="set-active-status" class="col-10 offset-1 col-md-6 offset-md-4">
    <% if @recipe.active? %>
      <button class="btn btn-danger" id ="make-inactive">
          Remove from Meal Suggestions
      </button> 
      <% else %>
        <button class="btn btn-success" id="activate">
          Add to Meal Suggestions
      </button> 
    <% end %> 
    <%=  hidden_field_tag(:recipe_id, @recipe.id, class: 'recipe-id') %>
  </div>
</div>
</br>
<div class="row">
  <div class="col-5 offset-1 col-md-2 offset-md-4"><footer><%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %></footer></div>
  <div class="col-5 col-md-2"><footer><%= link_to 'Back', recipes_path %></footer></div>
</div>
<script type="text/javascript">

$(function () {
      
      var recipeID = $(".recipe-id").val();

      var attributesHash = {};

    $( "body" ).on( "click", "button", function() {

      var klass = $(this).attr('class');
      var isActive = true;

      if(klass =="btn btn-danger"){
        isActive = false;
      }

      attributesHash["active"] = isActive;

      var recipe = {recipe: attributesHash};

      runUpdate(recipe);

    });

    function runUpdate(recipeHash){
              $.ajax({
                 url:'/recipes/' + recipeID,
                  type: 'PATCH',
                  dataType: 'script',
                  contentType: 'application/json',
                  data:  JSON.stringify(recipeHash),
                   headers: {
                    'X-Transaction': 'POST Example',
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                  },
               success: function(data){
               },
                  error: function (jqXHR, textStatus, errorThrown) {
           //     //     may want to do flash instead
                    console.log("there was an error with your update");
               }
            });

  } //end of function

});

</script>

app/views/recipes/update.js.erb
id = <%= j @recipe.id.to_s %>;
$("#set-active-status").load('/recipes/' + id + ' #set-active-status');