config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'

  resources :recipes do
        collection do
      get 'pantry'
    end
     match :recipes_using_pantry, via: [:get], on: :collection
  end

  #probably will want to restrict the routes later
  resources :ingredients

resources :meals do 
   collection do
      get 'planner'
    end 
    match :batch_create, via: [:post], on: :collection
  end

  get  '/signup',  to: 'users#new'
  get '/charts', to: 'users#charts'

  resources :users 

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPlanner</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
     <script src="https://use.fontawesome.com/83a3e41bee.js"></script>
</head>

  <body>
   <nav id="navbar-mp" class="navbar navbar-toggleable-sm navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Meal Planner</a>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
                 <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
              </li>
              <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarRecipeDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Recipes
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarRecipeDropdownMenuLink">
                  <%= link_to "All Recipes", root_path, class: "dropdown-item" %>
                  <%= link_to "Add New", new_recipe_path, class: "dropdown-item" %>
                  <%= link_to "Pantry", pantry_recipes_path, class: "dropdown-item" %>
                </div>
              </li>
              <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarMealsDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Meals
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarMealsDropdownMenuLink">
                  <%= link_to "Add New", new_meal_path, class: "dropdown-item" %>
                  <%= link_to "Recent Meals", meals_path, class: "dropdown-item" %>
                  <%= link_to "Planner", planner_meals_path, class: "dropdown-item" %>
               </div>
              </li>
               <li class="nav-item active dropdown">
                  <a href="#" id="navbarAccountDropdownMenuLink" class="nav-link dropdown-toggle" data-toggle="dropdown"> Account </a>
                  <div class="dropdown-menu" aria-labelledby="navbarAccountDropdownMenuLink">
                  <%= link_to "Charts", charts_path, class: "dropdown-item" %>
                    <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
                    <%= link_to "Log out", logout_path, method: "delete", class: "dropdown-item" %>
                  </div>
            </li>
            <% else %>
              <li><%= link_to "Log in", login_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>

    </nav>
  	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>